### ISSUE TITLE
Missing diagnostics

### ISSUE THREAD

**Issue by HiPhish** [scalameta/nvim-metals#132]
**Describe the bug**

I have been following this [Scala crash course](https://www.youtube.com/watch?v=-xRfJcwhy7A) on YouTube and I noticed that a number of diagnostics that he has in VSCode do not show up for me in Neovim. For example, at 53:32 he has a warning message show up which is not showing on my end.

**To Reproduce**

1. Create a new project, for example using `sbt new scala/hello-world.g8`
2. Open up a file such as `src/main/scala/Main.scala`
3. Import the build, wait for Metals to finish indexing
4. Introduce an error, such as changing `println` to `priln`

**Expected behavior**

An error diagnostic message should appear. Some diagnostics do appear, such as when changing `object` to `obect`, but some are missing. And I don´t know if this is related, but if there are multiple errors, only the first one is displayed.

**Screenshots**

Error is show as expected:
![Screenshot_20210429_121829](https://user-images.githubusercontent.com/4954650/116536887-ce79d480-a8e5-11eb-8715-134a4deab30c.png)
Multiple errors, but none are shown:
![Screenshot_20210429_121927](https://user-images.githubusercontent.com/4954650/116536890-d0439800-a8e5-11eb-9e38-695d180ee6cb.png)
Error is inside the object:
![Screenshot_20210429_122209](https://user-images.githubusercontent.com/4954650/116537026-f9642880-a8e5-11eb-9d3a-011b23273155.png)
Two errors, but only first one is shown:
![Screenshot_20210429_122015](https://user-images.githubusercontent.com/4954650/116536897-d174c500-a8e5-11eb-998b-05c8fd238827.png)

**Installation:**

- Operating system: Linux ([Void](https://voidlinux.org/))
- Nvim version: v0.5.0-dev+1236-g1b030f889
- Commit of nvim-metals: 484f37001d6f7af1c57aad5caaff54eaeb9fab46
- Metals version: 0.10.2

**Search terms**

diagnostics, error, warning

**Comment by ckipp01** [comment]
Thanks for the report/question @HiPhish.

So this is actually working as expected. Keep in mind that there are different types of diagnostics coming from Metals. Some are coming from Scalameta which are happening really quickly as you type and are being shown for things that it can easily tell are wrong with your code. The other type require compilation. In your examples, if I'm understanding them correct, they are all unsaved buffers? Meaning that the compile diagnostics won't appear like you're expecting until you save. Take you middle example where you say none are displayed. If you save it you end up with:

<img width="337" alt="Screenshot 2021-04-29 at 12 48 31" src="https://user-images.githubusercontent.com/13974112/116539726-852b8400-a8e9-11eb-944c-cc00195c280b.png">

Hope that clears it up.

**Comment by HiPhish** [comment]
> In your examples, if I'm understanding them correct, they are all unsaved buffers?

In the above example yes, but when I followed the above tutorial the same happens even when I save a buffer. Does compilation take a particularly long time? Do I need to set up an autocommand first? Do I need some special sbt settings?

**Comment by HiPhish** [comment]
Here is a screenshot, on the left is my buffer, on the right is sbt running in a terminal buffer. The Scala buffer is saved.

![Screenshot_20210429_133625](https://user-images.githubusercontent.com/4954650/116545171-62509e00-a8f0-11eb-9cfd-d21432613476.png)

**Comment by ckipp01** [comment]
> Here is a screenshot, on the left is my buffer, on the right is sbt running in a terminal buffer. The Scala buffer is saved.
> 
> ![Screenshot_20210429_133625](https://user-images.githubusercontent.com/4954650/116545171-62509e00-a8f0-11eb-9cfd-d21432613476.png)

🤔 so in such a small example like this is should be almost instantly.

<img width="1244" alt="Screenshot 2021-04-29 at 13 44 34" src="https://user-images.githubusercontent.com/13974112/116545797-2407ae80-a8f1-11eb-9401-b9df6db9cd60.png">

What does the result of your `:MetalsDoctor` look like?

**Comment by HiPhish** [comment]
`:MetalsDoctor` had green checkmarks on everything. I have run `sbt clean` and removed both the `.metals` and `.bloop` directory and now it´s working again, so maybe it was just a fluke. I did open Neovim another terminal with a different project at the same time, could that have been the problem? The directory layout is like this:

```
├── playground
│   ├── aliases.sbt
│   ├── build.sbt
│   ├── project
│   ├── sbt.sbt
│   ├── scalac.sbt
│   ├── scalafix.sbt
│   ├── src
│   ├── target
│   └── version.sbt
├── playground3
│   ├── aliases.sbt
│   ├── build.sbt
│   ├── project
│   ├── sbt.sbt
│   ├── src
│   ├── target
│   └── version.sbt
├── project
│   └── target
└── target
    ├── global-logging
    └── task-temp-directory
```

`playground` is the main project (the one I am following along) and `playground3` is a Scala 3 project. Could it be that two different metals instances can mess each other up?

**Comment by ckipp01** [comment]
O wow, that's an incredibly confusing layout. Off topic, but I'd advise pretty heavily against using a structure like this with a bunch of different sbt files at the root of your project.

However, to the point, Metals also may have issues with a layout like this. Is there also an sbt file at the root of where you're located? Meaning one layer above where you're showing? If so, Metals is probably marking that as the workspace root, meaning that it might be trying to detect if `playgournd` is it's own build target and if `playground3` is also it's own build target.

**Comment by HiPhish** [comment]
> O wow, that's an incredibly confusing layout. Off topic, but I'd advise pretty heavily against using a structure like this with a bunch of different sbt files at the root of your project.

It wasn´t my idea, I ran the template and that is what it produced. I am just trying to learn Scala here, but so far I have been spending more time trying to sort out its cryptic ecosystem.

> Is there also an sbt file at the root of where you're located? Meaning one layer above where you're showing?

No, the root directory is `~/Desktop/scala-crashcourse`, there I ran `sbt new devinsideyou/scala-seed.g8` to create the structure. It create the `playground`, `project` and `target` directories; only `playground` contains sbt files. Then I ran `g8 devinsideyou/scala3-seed.g8` to create the `playground3` project. See 23:30 in the video. When I work on a project I `cd` into its directory first. From my understanding the `playground` and `playground3` projects should not share any files, right?

**Comment by ckipp01** [comment]
> It wasn´t my idea, I ran the template and that is what it produced. I am just trying to learn Scala here, but so far I have been spending more time trying to sort out its cryptic ecosystem.

Noted. Sorry it's been confusing and cryptic for you so far.

> No, the root directory is ~/Desktop/scala-crashcourse, there I ran sbt new devinsideyou/scala-seed.g8 to create the structure. It create the playground, project and target directories; only playground contains sbt files. Then I ran g8 devinsideyou/scala3-seed.g8 to create the playground3 project. See 23:30 in the video. When I work on a project I cd into its directory first. From my understanding the playground and playground3 projects should not share any files, right?

So as far as I can tell, the `target` directory shouldn't be there and may be causing issues. I think this may be due to the fact that you ran sbt new, which created the `target` directory. To avoid this in the future, you can also just do `g8 new devinsideyou/scala3-seed.g8`, that is if you have g8 installed. sbt new is just a wrapper around that, however g8 is faster and won't create the `target` directory.

Without looking to deeply at the projects, yes my assumption is that you're correct and the two shouldn't share any code at all. So I'd recommend doing the following.

1. delete the `target` directory at the same level as your playground
2. delete any `.metals/` or `.bloop/` directories that may have been created at the same level as that top `target`.
3. Then as you are doing, `cd` into the directory and then ensure that the workspace root is indeed the current directory. You can tell by looking at the build targets in `:MetalsDoctor`.

**Comment by HiPhish** [comment]
OK, I´ll give it a try. I have set up the projects from scratch again and if I don´t post anything here it is working out fine. For the sake of completeness, here is the output of `:MetalsDoctor`

<details>
<summary>
Click to open
</summary>

```

╭ Metals Doctor ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│Build server currently being used is Bloop.                                                                                                                                             │
│                                                                                                                                                                                        │
│These are the installed build targets for this workspace. One build target corresponds to one classpath. For example, normally one sbt project maps to two build targets: main and test.│
│                                                                                                                                                                                        │
│## Build Targets                                                                                                                                                                        │
│                                                                                                                                                                                        │
│### playground                                                                                                                                                                          │
│  - scala version: 2.13.5                                                                                                                                                               │
│  - diagnostics: ✅                                                                                                                                                                     │
│  - goto definition: ✅                                                                                                                                                                 │
│  - completions: ✅                                                                                                                                                                     │
│  - find references: ✅                                                                                                                                                                 │
│                                                                                                                                                                                        │
│                                                                                                                                                                                        │
│### playground-test                                                                                                                                                                     │
│  - scala version: 2.13.5                                                                                                                                                               │
│  - diagnostics: ✅                                                                                                                                                                     │
│  - goto definition: ✅                                                                                                                                                                 │
│  - completions: ✅                                                                                                                                                                     │
│  - find references: ✅                                                                                                                                                                 │
│                                                                                                                                                                                        │
│                                                                                                                                                                                        │
│### playground-build                                                                                                                                                                    │
│  - scala version: 2.12.13                                                                                                                                                              │
│  - diagnostics: ✅                                                                                                                                                                     │
│  - goto definition: ✅                                                                                                                                                                 │
│  - completions: ✅                                                                                                                                                                     │
│  - find references: ✅                                                                                                                                                                 │
│                                                                                                                                                                                        │
│                                                                                                                                                                                        │
│### playground-build-build                                                                                                                                                              │
│  - scala version: 2.12.13                                                                                                                                                              │
│  - diagnostics: ✅                                                                                                                                                                     │
│  - goto definition: ✅                                                                                                                                                                 │
│  - completions: ✅                                                                                                                                                                     │
│  - find references: ✅                                                                                                                                                                 │
│                                                                                                                                                                                        │
│                                                                                                                                                                                        │
│### playground-build-build-build                                                                                                                                                        │
│  - scala version: 2.12.13                                                                                                                                                              │
│  - diagnostics: ✅                                                                                                                                                                     │
│  - goto definition: ✅                                                                                                                                                                 │
│  - completions: ✅                                                                                                                                                                     │
│  - find references: ✅                                                                                                                                                                 │
│                                                                                                                                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```
</details>

> Noted. Sorry it's been confusing and cryptic for you so far.

No need to apologize, you are not the one that created this mess.

**Comment by HiPhish** [comment]
Update: I think I have found something interesting. When I put my computer to sleep while Neovim with Metals is running, then wake it up diagnostics are not working. Executing `:MetalsBuildRestart` and/or `:MetalsCompileClean` seems to jolt Metals back into place.

**Comment by ckipp01** [comment]
Huh interesting. In that scenario before you do those, if  you do a `:MetalsLogsToggle` and hit save or anything do you see anything happening in the logs or is it complete not connected?

**Comment by HiPhish** [comment]
Here are my logs after waking up from sleep mode:

```
2021.04.30 11:53:59 INFO  compiling playground (1 scala source)
2021.04.30 11:53:59 INFO  time: compiled playground in 0.12s
2021.04.30 11:54:12 INFO  compiling playground (1 scala source)
2021.04.30 11:54:12 INFO  time: compiled playground in 0.47s
2021.04.30 11:54:29 INFO  compiling playground (1 scala source)
2021.04.30 11:54:29 INFO  time: compiled playground in 0.47s
2021.04.30 11:54:57 INFO  compiling playground (1 scala source)
2021.04.30 11:54:57 INFO  time: compiled playground in 0.47s
2021.04.30 11:55:07 INFO  compiling playground (1 scala source)
2021.04.30 11:55:07 INFO  time: compiled playground in 0.49s
```

Afterwards nothing happens when I write the buffer to file. Now I execute `:MetalsBuildRestart` and the log shows

<details>
<summary>
Click to open
</summary>

```
No more data in the client stdin, exiting...
No more data in the client stdin, exiting...
No more data in the server stdin, exiting...
Unexpected exception when forwarding server stdin ---> client stdout
No more data in the server stdin, exiting...
Unexpected exception when forwarding server stdin ---> client stdout
java.io.IOException: com.sun.jna.LastErrorException: [104] Connection reset by peer
        at bloop.sockets.UnixDomainSocket$UnixDomainSocketInputStream.doRead(UnixDomainSocket.java:171)
        at bloop.sockets.UnixDomainSocket$UnixDomainSocketInputStream.read(UnixDomainSocket.java:156)
        at java.base/java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:388)
        at bloop.launcher.bsp.BspBridge.copyContents(BspBridge.scala:289)
        at bloop.launcher.bsp.BspBridge.forwardStreamContents(BspBridge.scala:275)
        at bloop.launcher.bsp.BspBridge.$anonfun$wireBspConnectionStreams$2(BspBridge.scala:228)
        at bloop.bloopgun.core.Shell$$anon$2.run(Shell.scala:155)
Caused by: com.sun.jna.LastErrorException: [104] Connection reset by peer
        at bloop.sockets.UnixDomainSocketLibrary.read(Native Method)
        at bloop.sockets.UnixDomainSocket$UnixDomainSocketInputStream.doRead(UnixDomainSocket.java:169)
        ... 6 more
java.io.IOException: com.sun.jna.LastErrorException: [104] Connection reset by peer
        at bloop.sockets.UnixDomainSocket$UnixDomainSocketInputStream.doRead(UnixDomainSocket.java:171)
        at bloop.sockets.UnixDomainSocket$UnixDomainSocketInputStream.read(UnixDomainSocket.java:156)
        at java.base/java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:388)
        at bloop.launcher.bsp.BspBridge.copyContents(BspBridge.scala:289)
        at bloop.launcher.bsp.BspBridge.forwardStreamContents(BspBridge.scala:275)
        at bloop.launcher.bsp.BspBridge.$anonfun$wireBspConnectionStreams$2(BspBridge.scala:228)
        at bloop.bloopgun.core.Shell$$anon$2.run(Shell.scala:155)
Caused by: com.sun.jna.LastErrorException: [104] Connection reset by peer
        at bloop.sockets.UnixDomainSocketLibrary.read(Native Method)
        at bloop.sockets.UnixDomainSocket$UnixDomainSocketInputStream.doRead(UnixDomainSocket.java:169)
        ... 6 more
2021.04.30 12:21:26 ERROR timeout: build server 'bloop' during shutdown
2021.04.30 12:21:26 ERROR timeout: build server 'bloop' during shutdown
2021.04.30 12:21:26 INFO  Attempting to connect to the build server...
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /tmp/bsp-launcher2
508316164665476029/bsp.socket'...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
No server running at 127.0.0.1:8212, let's fire one...
Resolving ch.epfl.scala:bloop-frontend_2.12:1.4.8-19-4d9f966b...
Starting bloop server at 127.0.0.1:8212...
Attempting a connection to the server...
Attempting a connection to the server...
Attempting a connection to the server...
[D] Loading workspace settings from bloop.settings.json
[D] Loading 2 projects from '/home/hiphish/Desktop/scala-crashcourse/playground/.bloop'...
[D] Loading project from '/home/hiphish/Desktop/scala-crashcourse/playground/.bloop/playground.json'
[D] Loading project from '/home/hiphish/Desktop/scala-crashcourse/playground/.bloop/playground-test.json'
[D] Cache miss for scala instance org.scala-lang:scala-compiler:2.13.5.
[D]   => /home/hiphish/.cache/coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.3.1/jna-5.3.1.jar
[D]   => /home/hiphish/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline/3.19.0/jline-3.19.0.jar
[D]   => /home/hiphish/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.5/scala-compiler-2.13.5.jar
[D]   => /home/hiphish/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5.jar
[D]   => /home/hiphish/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.5/scala-reflect-2.13.5.jar
[D] Configured SemanticDB in projects 'playground', 'playground-test'
[D] Loading previous analysis for 'playground' from '/home/hiphish/Desktop/scala-crashcourse/playground/target/streams/compile/bloopAnalysisOut/_global/streams/inc_compile_2.13.zip'.
[D] Loading previous analysis for 'playground-test' from '/home/hiphish/Desktop/scala-crashcourse/playground/target/streams/test/bloopAnalysisOut/_global/streams/inc_compile_2.13.zip'.
[D] Waiting for a connection at local:///tmp/bsp-launcher2508316164665476029/bsp.socket...
The server is listening for incoming connections at local:///tmp/bsp-launcher250831616
4665476029/bsp.socket...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
2021.04.30 12:21:28 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/hiphish/.cache/metals/bsp.trace.json
2021.04.30 12:21:28 INFO  Attempting to connect to the build server...
Starting the bsp launcher for bloop...
2021.04.30 12:21:28 INFO  Attempting to connect to the build server...Opening a bsp server connection with 'bsp --protocol local --socket /tmp/bsp-launcher7028801205772518247/bsp.socket'...

Waiting for the bsp connection to come up...
Starting the bsp launcher for bloop...
2021.04.30 12:21:28 INFO Opening a bsp server connection with 'bsp --protocol local --socket /tmp/bsp-launcher10411600070847865779/bsp.socket'... Attempting to connect to the build server...

Waiting for the bsp connection to come up...
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /tmp/bsp-launcher2
10994644005877820/bsp.socket'...
Waiting for the bsp connection to come up...
[D] Loading workspace settings from bloop.settings.json
[D] Waiting for a connection at local:///tmp/bsp-launcher210994644005877820/bsp.socket...
The server is listening for incoming connections at local:///tmp/bsp-launcher210994644005877820/bsp.socket...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
2021.04.30 12:21:28 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/hiphish/.cache/metals/bsp.trace.json
[D] Loading workspace settings from bloop.settings.json
[D] Waiting for a connection at local:///tmp/bsp-launcher7028801205772518247/bsp.socket...
The server is listening for incoming connections at local:///tmp/bsp-launcher7028801205772518247/bsp.socket...
[D] Loading workspace settings from bloop.settings.json
[D] Waiting for a connection at local:///tmp/bsp-launcher10411600070847865779/bsp.socket...
The server is listening for incoming connections at local:///tmp/bsp-launcher10411600070847865779/bsp.socket...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
Starting thread that pumps server stdout and redirects it to the client stdout...
2021.04.30 12:21:28 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/hiphish/.cache/metals/bsp.trace.json
2021.04.30 12:21:28 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/hiphish/.cache/metals/bsp.trace.json
2021.04.30 12:21:28 INFO  time: Connected to build server in 1.45s
2021.04.30 12:21:28 INFO  Connected to Build server: Bloop v1.4.8-19-4d9f966b
Caught unexpected io exception handling event for /home/hiphish/Desktop/scala-crashcourse/playground/src/main/scala-2.13
java.nio.file.NoSuchFileException: /home/hiphish/Desktop/scala-crashcourse/playground/src/main/scala-2.13
        at com.swoval.files.NativeDirectoryLister.fillResults(NativeDirectoryLister.java:93)
        at com.swoval.files.NativeDirectoryLister.apply(NativeDirectoryLister.java:48)
        at com.swoval.files.SimpleFileTreeView$Lister.impl(SimpleFileTreeView.java:149)
        at com.swoval.files.SimpleFileTreeView$Lister.fillResults(SimpleFileTreeView.java:140)
        at com.swoval.files.SimpleFileTreeView.list(SimpleFileTreeView.java:50)
        at com.swoval.files.CachedDirectoryImpl.init(CachedDirectoryImpl.java:568)
        at com.swoval.files.CachedDirectoryImpl.init(CachedDirectoryImpl.java:557)
        at com.swoval.files.FileCacheDirectoryTree.newCachedDirectory(FileCacheDirectoryTree.java:623)
        at com.swoval.files.FileCacheDirectoryTree.handleEvent(FileCacheDirectoryTree.java:298)
        at com.swoval.files.FileTreeRepositories$1.onNext(FileTreeRepositories.java:79)
        at com.swoval.files.FileTreeRepositories$1.onNext(FileTreeRepositories.java:73)
        at com.swoval.files.Observers.onNext(Observers.java:31)
        at com.swoval.files.NioPathWatcher.runCallbacks(NioPathWatcher.java:423)
        at com.swoval.files.NioPathWatcher.handleEvent(NioPathWatcher.java:447)
        at com.swoval.files.NioPathWatcher.access$300(NioPathWatcher.java:35)
        at com.swoval.files.NioPathWatcher$2.accept(NioPathWatcher.java:108)
        at com.swoval.files.NioPathWatcher$2.accept(NioPathWatcher.java:102)
        at com.swoval.files.NioPathWatcherService$2.run(NioPathWatcherService.java:95)
2021.04.30 12:21:29 WARN  Could not find java sources in None. Java symbols will not be available.
2021.04.30 12:21:29 INFO  time: indexed workspace in 0.92s
2021.04.30 12:21:29 INFO  compiling playground (1 scala source)
2021.04.30 12:21:31 INFO  time: compiled playground in 1.53s
```
</details>

Afterwards I still need to execute `:MetalsCompileClean` to get any wrong diagnostics unstuck again.

```
2021.04.30 12:29:25 INFO  Deduplicating compilation of playground from bsp client 'Met
als 0.10.2' (since 7m 57.386s)
2021.04.30 12:29:25 INFO  compiling playground-test (2 scala sources)
2021.04.30 12:29:25 INFO  compiling playground-build (3 scala sources)
2021.04.30 12:29:27 INFO  time: compiled playground-test in 2.24s
2021.04.30 12:29:29 INFO  time: compiled playground-build in 3.42s
```

**Comment by ckipp01** [comment]
🤔 I've seen a report of that happening in the past, but am unsure if anything actually fixed it. @jsatk did this still happen to you at all where Metals is unresponsive after you close your laptop?

I find it odd that the `:MetalsCompileClean` would do anything to help in this situation, but I can see how `:MetalsBuildRestart` would. In this situation you can also try `:MetalsBuildConnect` and it should work and be faster than `:MetalsBuildRestart`.

**Comment by jsatk** [comment]
> 🤔 I've seen a report of that happening in the past, but am unsure if anything actually fixed it. @jsatk does this still happen to you at all where Metals is unresponsive after you close your laptop?
> 
> I find it odd that the `:MetalsCompileClean` would do anything to help in this situation, but I can see how `:MetalsBuildRestart` would. In this situation you can also try `:MetalsBuildConnect` and it should work and be faster than `:MetalsBuildRestart`.

Apologies for the late reply. Didn't check my email all weekend. 😄 

I have not seen this actually. In quite awhile. That doesn't mean it *is* fixed. It's possible I simply haven't encountered it lately. But it was definitely a very annoying problem for me before and now it's not so *anecdotally* I'd be it is fixed.
