### ISSUE TITLE
Stops Reporting Error

### ISSUE THREAD

**Issue by w-r-z-k** [scalameta/nvim-metals#305]
This file has syntax errors.  They are reported.  When I move the case class out of the object to resolve one error, the file now reports no errors.  But there are more errors.

<img width="1235" alt="Screen Shot 2021-12-18 at 3 40 23 PM" src="https://user-images.githubusercontent.com/3805659/146655014-06749fb1-517b-41f6-9026-1c70a01a219e.png">

Move the case class to the top and all errors disappear.

<img width="1236" alt="Screen Shot 2021-12-18 at 3 44 17 PM" src="https://user-images.githubusercontent.com/3805659/146655051-9c903a8b-e0b1-404c-87f0-0db6d286b611.png">

But really there are still errors:

```
Day15a. scala:27: error: not found: value
val Dijkstra. ShortestPath (lowestCost, shortestPath) = dijkstraContext. solve(A, E)
Day15a. scala:27: error: not found: value
Dijkstra. ShortestPath( lowestCost, shortestPath) = dijkstraContext. solve(A, E) or pasti
Day 15a. scala:29: error: not found: value res Mg Styling with Markdown is supported
println("answer1=" + res)
scalac Remember, contributions to this repository should follov
3 errors
```

**Comment by w-r-z-k** [comment]
Actually this is happening on all files now.  Maybe I hit some key to switch the display of error off?

**Comment by w-r-z-k** [comment]
It just completely stopped displaying errors.  No config changes.  Restarted the computer.  Just no longer working.  There were some recent patches I saw come through.  And I see this in the log:

```
[WARN  Fri 17 Dec 13:20:28 2021 2241694816595] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:552: Potential breaking change in commit 9a7c348 of scalameta/nvim-metals
[WARN  Fri 17 Dec 13:20:28 2021 2241694933230] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:552: Potential breaking change in commit 70210b2 of scalameta/nvim-metals
[WARN  Fri 17 Dec 13:20:28 2021 2241695031581] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:552: Potential breaking change in commit 6d3ffed of scalameta/nvim-metals
[WARN  Fri 17 Dec 13:20:28 2021 2241695124924] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:552: Potential breaking change in commit 2e008e6 of scalameta/nvim-metals
[WARN  Fri 17 Dec 13:20:28 2021 2241695218851] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:552: Potential breaking change in commit 6d35d76 of scalameta/nvim-metals
[WARN  Fri 17 Dec 13:20:28 2021 2241695310514] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:552: Potential breaking change in commit 2d49173 of scalameta/nvim-metals
[WARN  Fri 17 Dec 13:20:28 2021 2241695401556] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:552: Potential breaking change in commit deaf932 of scalameta/nvim-metals
[WARN  Fri 17 Dec 13:20:50 2021 2263921438890] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:552: Potential breaking change in commit 9a7c348 of scalameta/nvim-metals
[WARN  Fri 17 Dec 13:20:50 2021 2263921548490] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:552: Potential breaking change in commit 70210b2 of scalameta/nvim-metals
[WARN  Fri 17 Dec 13:20:50 2021 2263921649892] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:552: Potential breaking change in commit 6d3ffed of scalameta/nvim-metals
[WARN  Fri 17 Dec 13:20:50 2021 2263921748604] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:552: Potential breaking change in commit 2e008e6 of scalameta/nvim-metals
[WARN  Fri 17 Dec 13:20:50 2021 2263921847214] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:552: Potential breaking change in commit 6d35d76 of scalameta/nvim-metals
[WARN  Fri 17 Dec 13:20:50 2021 2263922007174] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:552: Potential breaking change in commit 2d49173 of scalameta/nvim-metals
[WARN  Fri 17 Dec 13:20:50 2021 2263922154495] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:552: Potential breaking change in commit deaf932 of scalameta/nvim-metals
```

**Comment by w-r-z-k** [comment]
I deleted the `.metals` folder in the root of my project and it started working again

**Comment by ckipp01** [comment]
So in last image in your first message I see your status is "Compiling 7m..", something is definitely going wrong if you are setting the status say that for 7 min. As for the breaking changes that packer is reporting, none of those have to do with Metals actually, but the LSP integration with Neovim and nvim-metals. Or related to changes in 0.6, so that should be the issue here. If you are able to reproduce this again, let me know.

**Comment by w-r-z-k** [comment]
Even when it's working I get the infinitely increasing compile time.  I just thought that was normal.

Unfortunately I can't reproduce it now that the project `.metals` folder was wiped.

MacOS 11.6.1
NVIM v0.6.0
metals 0.10.9
nvim-metals: not sure where I would find that but PackerSync is up-to-date

# Note:
#   Supported Scala versions:
#     Scala 3: 3.0.0, 3.0.1, 3.0.2, 3.1.0, 3.1.1-RC1
#     Scala 2:
#       2.11.12
#       2.12.15, 2.12.14, 2.12.13, 2.12.12, 2.12.11, 2.12.8, 2.12.9, 2.12.10
#       2.13.7, 2.13.4, 2.13.5, 2.13.6, 2.13.0, 2.13.1, 2.13.2, 2.13.3

## Current settings
{
  excludedPackages = { "akka.actor.typed.javadsl", "com.github.swagger.akka.javadsl" },
  showImplicitArguments = true,
  superMethodLensesEnabled = true
}

**Comment by w-r-z-k** [comment]
Now it's doing it again and wiping the project .metals folder doesn't resolve it.

There is a log in there though and some errors:



```
[0m2021.12.18 21:44:19 INFO  Started: Metals version 0.10.9 in workspace '/Users/user/Development/aoc2021' for client Neovim 0.6.0.[0m
[0m2021.12.18 21:44:20 INFO  time: initialize in 1.35s[0m
[0m2021.12.18 21:44:21 INFO  Attempting to connect to the build server...[0m
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /var/folders/tv/txzykxv91r14p77lj4g2smn80000gn/T/bsp-launcher4264961629728296553/bsp.socket'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Loading workspace settings from bloop.settings.json
[0m[32m[D][0m Waiting for a connection at local:///var/folders/tv/txzykxv91r14p77lj4g2smn80000gn/T/bsp-launcher4264961629728296553/bsp.socket...
The server is listening for incoming connections at local:///var/folders/tv/txzykxv91r14p77lj4g2smn80000gn/T/bsp-launcher4264961629728296553/bsp.socket...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
[0m2021.12.18 21:44:21 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /Users/user/Library/Caches/org.scalameta.metals/bsp.trace.json[0m
[0m2021.12.18 21:44:21 INFO  Attempting to connect to the build server...[0m
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /var/folders/tv/txzykxv91r14p77lj4g2smn80000gn/T/bsp-launcher8182771565541700846/bsp.socket'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Loading workspace settings from bloop.settings.json
[0m[32m[D][0m Waiting for a connection at local:///var/folders/tv/txzykxv91r14p77lj4g2smn80000gn/T/bsp-launcher8182771565541700846/bsp.socket...
The server is listening for incoming connections at local:///var/folders/tv/txzykxv91r14p77lj4g2smn80000gn/T/bsp-launcher8182771565541700846/bsp.socket...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
[0m2021.12.18 21:44:21 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /Users/user/Library/Caches/org.scalameta.metals/bsp.trace.json[0m
[0m2021.12.18 21:44:21 INFO  time: Connected to build server in 0.46s[0m
[0m2021.12.18 21:44:21 INFO  Connected to Build server: Bloop v1.4.11[0m
Default dialect is deprecated; use explicit: [Scala211,scala212,Scala212Source3,scala213,Scala213Source3,Sbt0137,Sbt1,scala3]
Also see https://scalameta.org/scalafmt/docs/configuration.html#scala-dialects"
[0m2021.12.18 21:44:27 INFO  running '/Users/user/Library/Caches/Coursier/jvm/adopt@1.11.0-11/Contents/Home/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /var/folders/tv/txzykxv91r14p77lj4g2smn80000gn/T/metals15690715502629878641/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'[0m
[0m2021.12.18 21:44:28 INFO  time: indexed workspace in 6.66s[0m
[0m2021.12.18 21:44:28 INFO  compiling aoc2021 (5 scala sources)[0m
[0m2021.12.18 21:44:29 INFO  [info] welcome to sbt 1.5.4 (AdoptOpenJDK Java 11.0.11)[0m
[0m2021.12.18 21:44:29 INFO  [info] loading settings for project aoc2021-build-build from metals.sbt ...[0m
[0m2021.12.18 21:44:30 INFO  no build target: using presentation compiler with only scala-library: 2.13.7[0m
[0m2021.12.18 21:44:31 INFO  time: compiled aoc2021 in 2.92s[0m
[0m2021.12.18 21:44:31 INFO  compiling aoc2021 (5 scala sources)[0m
[0m2021.12.18 21:44:31 INFO  time: compiled aoc2021 in 73ms[0m
[0m2021.12.18 21:44:31 INFO  [info] loading project definition from /Users/user/Development/aoc2021/project/project[0m
[0m2021.12.18 21:44:32 INFO  [info] loading settings for project aoc2021-build from metals.sbt ...[0m
[0m2021.12.18 21:44:32 INFO  [info] loading project definition from /Users/user/Development/aoc2021/project[0m
[0m2021.12.18 21:44:35 INFO  [success] Generated .bloop/aoc2021-build.json[0m
[0m2021.12.18 21:44:35 INFO  [success] Total time: 2 s, completed Dec. 18, 2021, 9:44:35 p.m.[0m
[0m2021.12.18 21:44:35 INFO  [info] loading settings for project aoc2021 from build.sbt ...[0m
[0m2021.12.18 21:44:35 INFO  [info] set current project to aoc2021 (in build file:/Users/user/Development/aoc2021/)[0m
[0m2021.12.18 21:44:35 INFO  [success] Generated .bloop/aoc2021-test.json[0m
[0m2021.12.18 21:44:35 INFO  [success] Generated .bloop/aoc2021.json[0m
[0m2021.12.18 21:44:35 INFO  [success] Total time: 0 s, completed Dec. 18, 2021, 9:44:36 p.m.[0m
[0m2021.12.18 21:44:36 INFO  time: ran 'sbt bloopInstall' in 8.67s[0m
[0m2021.12.18 21:44:36 INFO  Disconnecting from Bloop session...[0m
[0m2021.12.18 21:44:36 INFO  Shut down connection with build server.[0m
No more data in the server stdin, exiting...
No more data in the server stdin, exiting...
[0m2021.12.18 21:44:36No more data in the server stdin, exiting...
No more data in the server stdin, exiting...
 INFO  Shut down connection with build server.[0m
No more data in the client stdin, exiting...
No more data in the client stdin, exiting...
[0m2021.12.18 21:44:36 INFO  Attempting to connect to the build server...[0m
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /var/folders/tv/txzykxv91r14p77lj4g2smn80000gn/T/bsp-launcher11142430229973041701/bsp.socket'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Loading workspace settings from bloop.settings.json
[0m[32m[D][0m Waiting for a connection at local:///var/folders/tv/txzykxv91r14p77lj4g2smn80000gn/T/bsp-launcher11142430229973041701/bsp.socket...
The server is listening for incoming connections at local:///var/folders/tv/txzykxv91r14p77lj4g2smn80000gn/T/bsp-launcher11142430229973041701/bsp.socket...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
[0m2021.12.18 21:44:36 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /Users/user/Library/Caches/org.scalameta.metals/bsp.trace.json[0m
[0m2021.12.18 21:44:36 INFO  Attempting to connect to the build server...[0m
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /var/folders/tv/txzykxv91r14p77lj4g2smn80000gn/T/bsp-launcher11832103162469645505/bsp.socket'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Loading workspace settings from bloop.settings.json
[0m[32m[D][0m Waiting for a connection at local:///var/folders/tv/txzykxv91r14p77lj4g2smn80000gn/T/bsp-launcher11832103162469645505/bsp.socket...
The server is listening for incoming connections at local:///var/folders/tv/txzykxv91r14p77lj4g2smn80000gn/T/bsp-launcher11832103162469645505/bsp.socket...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
[0m2021.12.18 21:44:36 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /Users/user/Library/Caches/org.scalameta.metals/bsp.trace.json[0m
[0m2021.12.18 21:44:36 INFO  time: Connected to build server in 92ms[0m
[0m2021.12.18 21:44:36 INFO  Connected to Build server: Bloop v1.4.11[0m
[0m2021.12.18 21:44:38 INFO  time: indexed workspace in 1.75s[0m
[0m2021.12.18 21:44:38 INFO  compiling aoc2021 (5 scala sources)[0m
[0m2021.12.18 21:44:39 INFO  no build target: using presentation compiler with only scala-library: 2.13.7[0m
[0m2021.12.18 21:44:39 INFO  time: compiled aoc2021 in 1.02s[0m
[0m2021.12.18 21:44:55 INFO  compiling aoc2021 (5 scala sources)[0m
[0m2021.12.18 21:44:55 INFO  time: compiled aoc2021 in 59ms[0m
[0m2021.12.18 21:45:07 INFO  shutting down Metals[0m
[0m2021.12.18 21:45:07 INFO  Shut down connection with build server.[0mNo more data in the server stdin, exiting...

No more data in the server stdin, exiting...
[0m2021.12.18 21:45:07 INFO No more data in the server stdin, exiting... Shut down connection with build server.
[0m
No more data in the server stdin, exiting...
No more data in the client stdin, exiting...
No more data in the client stdin, exiting...
[0m2021.12.18 21:45:11 INFO  Started: Metals version 0.10.9 in workspace '/Users/user/Development/aoc2021' for client Neovim 0.6.0.[0m
[0m2021.12.18 21:45:12 INFO  time: initialize in 1.23s[0m
[0m2021.12.18 21:45:13 INFO  Attempting to connect to the build server...[0m
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /var/folders/tv/txzykxv91r14p77lj4g2smn80000gn/T/bsp-launcher6688322353862096573/bsp.socket'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Loading workspace settings from bloop.settings.json
[0m[32m[D][0m Waiting for a connection at local:///var/folders/tv/txzykxv91r14p77lj4g2smn80000gn/T/bsp-launcher6688322353862096573/bsp.socket...
The server is listening for incoming connections at local:///var/folders/tv/txzykxv91r14p77lj4g2smn80000gn/T/bsp-launcher6688322353862096573/bsp.socket...
[0m2021.12.18 21:45:12 INFO  skipping build import with status 'Installed'[0m
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
[0m2021.12.18 21:45:13 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /Users/user/Library/Caches/org.scalameta.metals/bsp.trace.json[0m
[0m2021.12.18 21:45:13 INFO  Attempting to connect to the build server...[0m
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /var/folders/tv/txzykxv91r14p77lj4g2smn80000gn/T/bsp-launcher5085738971105935403/bsp.socket'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Loading workspace settings from bloop.settings.json
[0m[32m[D][0m Waiting for a connection at local:///var/folders/tv/txzykxv91r14p77lj4g2smn80000gn/T/bsp-launcher5085738971105935403/bsp.socket...
The server is listening for incoming connections at local:///var/folders/tv/txzykxv91r14p77lj4g2smn80000gn/T/bsp-launcher5085738971105935403/bsp.socket...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
[0m2021.12.18 21:45:13 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /Users/user/Library/Caches/org.scalameta.metals/bsp.trace.json[0m
[0m2021.12.18 21:45:13 INFO  time: Connected to build server in 0.33s[0m
[0m2021.12.18 21:45:13 INFO  Connected to Build server: Bloop v1.4.11[0m
Default dialect is deprecated; use explicit: [Scala211,scala212,Scala212Source3,scala213,Scala213Source3,Sbt0137,Sbt1,scala3]
Also see https://scalameta.org/scalafmt/docs/configuration.html#scala-dialects"
[0m2021.12.18 21:45:17 INFO  time: indexed workspace in 4.11s[0m
[0m2021.12.18 21:45:17 INFO  compiling aoc2021 (5 scala sources)[0m
[0m2021.12.18 21:45:18 INFO  no build target: using presentation compiler with only scala-library: 2.13.7[0m
Dec. 18, 2021 9:45:19 P.M. org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNING: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "build/taskFinish",
  "params": {
    "taskId": {
      "id": "1"
    },
    "eventTime": 1639881917663,
    "message": "Compiled \u0027aoc2021\u0027",
    "status": 2,
    "dataKind": "compile-report",
    "data": {
      "target": {
        "uri": "file:/Users/user/Development/aoc2021/?id\u003daoc2021"
      },
      "errors": 1,
      "warnings": 1,
      "isNoOp": false,
      "isLastCycle": true
    }
  }
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.NullPointerException
	at scala.meta.internal.metals.Compilers.$anonfun$didCompile$1(Compilers.scala:227)
	at scala.meta.internal.metals.Compilers.$anonfun$didCompile$1$adapted(Compilers.scala:227)
	at scala.Option.foreach(Option.scala:407)
	at scala.meta.internal.metals.Compilers.didCompile(Compilers.scala:227)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$updateWorkspaceDirectory$10(MetalsLanguageServer.scala:407)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$updateWorkspaceDirectory$10$adapted(MetalsLanguageServer.scala:405)
	at scala.meta.internal.metals.ForwardingMetalsBuildClient.$anonfun$buildTaskFinish$2(ForwardingMetalsBuildClient.scala:172)
	at scala.Option.foreach(Option.scala:407)
	at scala.meta.internal.metals.ForwardingMetalsBuildClient.$anonfun$buildTaskFinish$1(ForwardingMetalsBuildClient.scala:169)
	at scala.meta.internal.metals.ForwardingMetalsBuildClient.$anonfun$buildTaskFinish$1$adapted(ForwardingMetalsBuildClient.scala:168)
	at scala.Option.foreach(Option.scala:407)
	at scala.meta.internal.metals.ForwardingMetalsBuildClient.buildTaskFinish(ForwardingMetalsBuildClient.scala:168)
	... 16 more

[0m2021.12.18 21:45:19 INFO  compiling aoc2021 (5 scala sources)[0m
[0m2021.12.18 21:45:19 INFO  time: compiled aoc2021 in 68ms[0m
[0m
2021.12.18 21:46:51 INFO  shutting down Metals[0m
[0mNo more data in the server stdin, exiting...2021.12.18 21:46:51
No more data in the server stdin, exiting... 
INFO  Shut down connection with build server.[0m
No more data in the server stdin, exiting...
[0mNo more data in the server stdin, exiting...2021.12.18 21:46:51
 INFO  Shut down connection with build server.[0m
No more data in the client stdin, exiting...
No more data in the client stdin, exiting...

```

**Comment by w-r-z-k** [comment]
I submitted a better a description of this in Issue #306 so I will close this one.
